site_name: Rust Notes
nav:
  - "大纲": index.md
  - "Rust 开发工具安装": rust_intro.md
  - "Rust 基本语法": rust_basic_syntax.md
  - "Rust 参考": rust_reference.md
theme:
  name: material

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true

# 引入 Mermaid 的 JavaScript 库
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.js
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# 可选：自定义 Mermaid 主题或配置
extra_css:
  - https://cdn.jsdelivr.net/npm/mermaid@10.6.1/dist/mermaid.min.css